### ISSUE TITLE
 May I know the inference time and model parameter size of your method on the KItti dataset？

### ISSUE THREAD

**Issue by MerlinGarcia** [princeton-vl/OGNI-DC#1]

**Comment by MerlinGarcia** [comment]
May I know the inference time and model parameter size of your method on the KITTI dataset？

**Comment by zuoym15** [comment]
The inference time is 435ms and the parameter count is 80.5M (CompletionFormer has 268ms and 79.7M, as a reference).  Please see Tab. 5 in our paper for details.
