### ISSUE TITLE
How to run on Custom data?

### ISSUE THREAD

**Issue by aniket-gupta1** [princeton-vl/OGNI-DC#2]
Hi, thanks for your amazing work. 

Can you provide some pointers as to what's the easiest way to run your model on custom data?

**Comment by zuoym15** [comment]
Hi, thank you for your interest in our work! 

I would recommend modifying based on the DDAD dataloader (src/data/ddad.py). You just need the RGB image and the sparse depth map (in meters) and can set the intrinsic and the gt to be zeros. 

Feel free to post an update if you run into any specific issues.
