### ISSUE TITLE
Unable to Access VOID Data - 404 Error

### ISSUE THREAD

**Issue by siyuanseever** [princeton-vl/OGNI-DC#5]
Hi,

I am currently unable to access the VOID data from the provided links in the README file. Each link results in a 404 error. Here are the specific links that are not working:

[VOID Data Part 1](https://drive.google.com/open?id=1kZ6ALxCzhQP8Tq1enMyNhjclVNzG8ODA)
[VOID Data Part 2](https://drive.google.com/open?id=1ys5EwYK6i8yvLcln6Av6GwxOhMGb068m)
[VOID Data Part 3](https://drive.google.com/open?id=1bTM5eh9wQ4U8p2ANOGbhZqTvDOddFnlI)
I have followed the instructions to navigate to the datasets directory, but the links appear to be broken.

Could you please check the links or provide an alternative way to download the VOID data?

Thank you for your assistance.

**Comment by zuoym15** [comment]
Hi,

We now host the download link ourselves: https://drive.google.com/file/d/1rzTFD35OCxMIguxLDcBxuIdhh5T2G7h4/view?usp=sharing. We also updated the readme accordingly. Thank you for catching this and let me know if you have any problem using the new link.
